server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     #mysql数据包
    url: jdbc:mysql://54.95.200.206:3306/cloud20?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.daisy.springcloud.entities   #所有entity别名类所在的包
  mapper-locations: classpath:mapper/*.xml
